# frozen_string_literal: true
source "https://rubygems.org"

gem 'cucumber', '~> 2.4.0'
gem 'capybara', '~> 2.12.0'
gem 'rspec', '~> 3.5.0'
gem 'site_prism', '~> 2.9'
gem 'selenium-webdriver', '~> 3.0.5'
gem 'parallel_tests', '~> 2.13.0'
gem 'cukeforker', '~> 1.1.0'
gem 'xml-simple', '~> 1.1.5'